In [1]:
import pandas as pd
import sys
from pathlib import Path
import polars as pl
sys.path.append(str(Path("..").resolve()))
from src.services import bloomberg_client
from src.parsers import extract_ucf

In [10]:
nbf_file = Path(r"C:\Users\mmoin\PYTHON PROJECTS\Commissions Report\data\raw\Broker Data\NBF\NBF_Q1_2026.xlsx")
mydf = pd.read_excel(nbf_file, header=None)
mydf.columns = ["Region", "Branch"] + mydf.iloc[0, 2:].astype(str).str.replace(".","/").tolist()
df = pd.DataFrame(mydf.iloc[2:, :].values, columns=mydf.columns)
df = df[df.iloc[:, 0].astype(str).str.upper().isin(["GRAND TOTAL","TOTAL"]) == False]
df = df.loc[:, ~df.columns.str.upper().isin(["GRAND TOTAL","TOTAL"])]
df = df.reset_index(drop=True)

In [ ]:
df[df.columns[2:]] = df[df.columns[2:]].apply(pd.to_numeric, errors='coerce')
df = df.replace(r"^\s*$", pd.NA, regex=True)
df = df.dropna(how='all').reset_index(drop=True)
df

,Region,Branch,HHL,HPYM,HUTL,HPYT,HTA,HHL/U,HBF,HHIS,...,APLE,TRVL/U,HTA/B,HHIS/U,HBIX,SHPE,MSTY,NFLY,HPYT/B,RDDY
0,RN,Laval,13993322.52,26449199.60,0.00,81900.00,19812.00,1.402260e+05,780993.52,149996.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,B1,Vancouve,15750244.36,656201.23,2754105.75,2871553.23,2743598.78,1.007096e+06,1847283.87,1954584.24,...,0.00,0.00000,0.0,16660.374920,0.0,0.0,0.0,0.0,0.0,0.0
2,M2,PVM Mont,12483157.64,3233669.31,3772437.48,1524019.77,3547817.39,2.991566e+05,652255.39,152041.40,...,0.00,0.00000,9145.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,PR,Calgary,21057585.08,404596.99,1494010.80,49140.00,525463.77,7.243100e+05,537373.15,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,RS,DIX30,1032272.20,4025761.35,3261294.72,33742.80,538176.47,7.554248e+06,236865.50,231812.00,...,0.00,0.00000,11888.5,0.000000,0.0,6440.0,0.0,0.0,1774.8,0.0
5,PR,WINNIPEG,3344104.04,1084903.02,644327.28,2839857.93,487391.71,1.872713e+05,35208.40,111659.36,...,0.00,0.00000,0.0,0.000000,0.0,4427.5,0.0,0.0,0.0,0.0
6,B1,White Ro,8451251.38,0.00,439934.40,50778.00,125228.35,1.606009e+04,1015386.52,17532.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
7,TR,Toronto,3700279.48,68574.00,4029012.36,10114.65,335053.94,1.809437e+05,116247.06,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
8,PR,Medicine,216805.78,0.00,0.00,5588995.23,369130.58,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
9,RN,St-Jerom,2115644.98,3185677.90,0.00,0.00,135547.10,3.495746e+04,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
10,RS,St-Jean-,364663.12,1100051.64,648622.26,363414.87,0.00,4.587082e+05,310852.59,0.00,...,0.00,29585.64808,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
11,OE,ANCASTER,1715572.32,0.00,170996.40,0.00,1059925.49,6.839456e+04,1451614.64,15584.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
12,TR,Barrie,734700.84,727.30,0.00,20475.00,666838.90,2.569614e+04,843933.48,68180.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
13,QC,Beauce,3650847.12,0.00,0.00,0.00,4953.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
14,B1,Kelowna,2194393.34,0.00,214447.95,0.00,209280.76,0.000000e+00,69576.15,4870.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
15,AT,Halifax,2378225.60,0.00,77269.50,0.00,41506.14,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
16,OE,Waterloo,0.00,0.00,0.00,27027.00,0.00,0.000000e+00,0.00,435874.74,...,0.00,0.00000,0.0,1342.935249,11949.1,0.0,0.0,0.0,0.0,0.0
17,B1,Victoria,363623.10,0.00,0.00,11056.50,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
18,PR,EDMONTON,1388273.14,0.00,0.00,0.00,0.00,0.000000e+00,0.00,126620.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
19,TR,Windsor,717571.92,0.00,0.00,0.00,522508.48,5.353363e+04,0.00,67254.70,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
20,OE,LONDON-C,0.00,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
21,QC,Chicouti,0.00,0.00,0.00,0.00,0.00,0.000000e+00,0.00,934260.80,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
22,M2,Kirkland,50954.00,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,30877.92,0.00000,0.0,0.000000,0.0,0.0,0.0,2223.0,0.0,443.0
23,TR,London,268730.00,0.00,0.00,0.00,0.00,1.070673e+05,145383.00,48700.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
24,AT,Moncton,186156.60,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25,QC,Quebec S,143090.00,0.00,0.00,0.00,242366.80,0.000000e+00,136976.50,24057.80,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
26,PR,Edmonton,75942.40,0.00,0.00,0.00,0.00,0.000000e+00,303810.91,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
27,OE,PETERBOR,151221.70,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
28,PR,SASKATOO,18148.00,44677.00,0.00,0.00,0.00,0.000000e+00,14835.00,15584.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
29,OE,OTTAWA,90181.60,0.00,20070.00,0.00,0.00,0.000000e+00,2472.50,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,4950.0,0.0,0.0,0.0
30,M2,Gatineau,0.00,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
31,QC,Québec,145170.04,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
32,QC,Rimouski,56293.70,0.00,0.00,9009.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
33,OE,Mississa,33504.00,0.00,0.00,13923.00,12877.80,0.000000e+00,3382.38,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
34,RN,Repentig,45893.50,0.00,0.00,0.00,0.00,0.000000e+00,13450.40,19480.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
35,PR,Regina,41880.00,0.00,0.00,0.00,0.00,0.000000e+00,59340.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
36,RS,Sorel,28618.00,0.00,0.00,45864.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
37,OE,North Ba,48615.70,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
38,OE,OAKVILLE,14357.86,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
39,RN,Shawinig,0.00,0.00,39056.22,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
40,RN,Trois-Ri,0.00,0.00,0.00,0.00,33020.00,0.000000e+00,13252.60,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
41,OE,Sudbury,31061.00,0.00,0.00,0.00,14859.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
42,RN,Joliette,0.00,0.00,0.00,0.00,0.00,0.000000e+00,16911.90,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
43,C3,HYBRID M,13262.00,0.00,0.00,0.00,8255.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
44,PR,Calgary,0.00,0.00,0.00,0.00,20967.70,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
45,RS,Victoria,0.00,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
46,B1,Sidney,13611.00,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
47,RS,Drummond,10470.00,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
48,B1,RICHMOND,10421.14,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
49,RS,Granby,0.00,7761.33,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50,PR,Red Deer,0.00,0.00,0.00,0.00,0.00,1.980744e+03,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
51,1859,Private Banking 1859,0.00,0.00,0.00,0.00,0.00,0.000000e+00,0.00,0.00,...,0.00,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df = pd.read_excel(r"C:\Users\mmoin\PYTHON PROJECTS\Commissions Report\data\raw\Broker Data\BMO\BMO_Q1_2026.xlsx", header=None)
search_grid = df.iloc[0:6,0:6].astype(str).apply(lambda x: x.str.strip().str.upper())
found = (search_grid == "BRANCH").stack()
if not found.any():
    raise ValueError("Could not find 'Branch' in the first 6 rows and columns.")
anchor_row, anchor_col = found.idxmax()
df_new = pd.DataFrame(data=df.iloc[anchor_row+1:, anchor_col:].values, columns=df.iloc[anchor_row, anchor_col:])
df_new = df_new.replace(r"^\s*$", pd.NA, regex=True)
df_new = df_new.dropna(how='all').reset_index(drop=True)
totals_mask = df_new["Branch"].astype(str).str.upper().isin(["TOTAL", "GRAND TOTAL", "TOTALS"])
if totals_mask.any():
    totals_idx = df_new[totals_mask].index[0]
    df_new = df_new.iloc[:totals_idx]
df_new = df_new.dropna(how='all').reset_index(drop=True)
# drop the column with "TOTAL" header if it exists
df_new = df_new.loc[:, ~df_new.columns.str.upper().isin(["TOTAL", "GRAND TOTAL", "TOTALS"])]

# df_new = df_new.replace(r"^\s*$", pd.NA, regex=True)
# df_new = df_new.dropna(how='all').reset_index(drop=True)
# df_new[df_new.columns] = df_new[df_new.columns].apply(pd.to_numeric, errors='coerce')
# df_new = df_new[df_new["Branch"].str.upper() != "TOTAL"].reset_index(drop=True)
# df_new.head()

3,Branch,Total,HHL,HHL.U,HBF,HTA,HUTL,HDIF,HHIS,HPYT,...,APLE,COSY,MSFH.U,RYHE,CRCY,TRVI,SOFY,CONY,AMZH.U,NaN
0,GTA WEST,56405.714,20742.765,11012.333,2599.807,5473.036,1539.525,737.66,1468.125,857.697,...,NaN,NaN,NaN,NaN,NaN,NaN,13.631,NaN,NaN,NaN
1,MONTREAL ST. JACQUES,31601.186,16514.97,868.434,2128.596,122.116,1925.892,2283.217,376.248,326.237,...,7.61,NaN,NaN,15.939,NaN,NaN,NaN,NaN,NaN,NaN
2,Laval,18759.998,12653.749,915.167,391.511,20.548,509.211,560.849,497.961,101.943,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.992,NaN,NaN
3,VAN SUBURBAN AND FRASER VALLEY,15752.102,3089.236,350.94,390.464,5170.552,864.398,20.755,621.254,23.607,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ottawa - West,15105.059,3972.027,9907.673,226.162,125.875,NaN,122.68,NaN,1.999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN